language: objective-c

xcode_project: Meridian/Meridian.xcodeproj
osx_image: xcode9.2

sudo: true

before_install:
  - brew install ldid

after_script: ./script/post_build.sh

notifications:
  webhooks: http://api.sparkes.zone/meridian-travis

addons:
  artifacts:
    target_paths:
      - Meridian/Meridian.ipa
