language: objective-c
xcode_project: Meridian/Meridian.xcodeproj
osx_image: xcode9.2
sudo: true
before_install:
- openssl aes-256-cbc -K $encrypted_e98fc6d03aa6_key -iv $encrypted_e98fc6d03aa6_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- brew install ldid
after_script: "./script/post_build.sh"
notifications:
  webhooks: http://api.sparkes.zone/meridian-travis
