language: objective-c
xcode_project: Meridian/Meridian.xcodeproj
osx_image: xcode9.2
sudo: true
before_install:
- openssl aes-256-cbc -K $encrypted_e98fc6d03aa6_key -iv $encrypted_e98fc6d03aa6_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- gem install xcpretty -N
- brew install ldid
- export THEOS=~/theos
- mkdir $THEOS
- git clone --recursive git://github.com/theos/theos.git $THEOS
- export PATH=$THEOS/bin:$PATH
- wget -O $THEOS/lib/libsubstrate.dylib http://dl.sparko.me/travis/libsubstrate.dylib
- wget -O $THEOS/include/substrate.h http://dl.sparko.me/travis/substrate.h
after_script: "./script/post_build.sh"
notifications:
  webhooks: http://api.sparkes.zone/meridian-travis
