#!/bin/bash

currDir=$(dirname $0)

echo "Found current dir: $currDir"

binCount=$(ls -1q  $currDir/bins | wc -l | sed -e 's/^[ `t]*//')

echo "Found $binCount bins"

echo "Giving all bins correct permissions (0777) and signing..."

for file in $currDir/bins/*
do
  jtool --sign sha1 --inplace --ent $currDir/ent.plist $file
  chmod 0777 $file
done

echo "Packing the binpack..."

cd $currDir
tar -cf bootstrap.tar ./bins/*

echo "Packed $binCount bins from $currDir/bins into $currDir/bootstrap.tar!"

cp $currDir/bootstrap.tar $currDir/../Meridian/Meridian/bootstrap.tar
